# -*- coding:utf-8 -*-
# Author:      zhousf
# Date:        2019-10-16
# File:        part.py
# Description:

part_english_name = {
    "boliposun": "Glass breakage",
    "boliliewen": "Glass breakage",
    "huahen": "Scratch",
    "guaca": "Scratch",
    "aoxian": "Sunken",
    "zhezhou": "Fold",
    "silie": "Tearing",
    "jichuan": "Breakdown",
    "queshi": "Missing",
    "XingLiXiangGai": "Trunk lid",
    "HouBaoXianGangPi": "Rear bumper",
    "FaDongJiZhao": "Hood",
    "ZhongWang": "Grille",
    "HouYeZiBan-Z": "Fender of left rear",
    "HouYeZiBan-Y": "Fender of right rear",
    "NeiWeiDeng-Z": "Inner Taillight of left",
    "NeiWeiDeng-Y": "Inner Taillight of right",
    "HouMen-Z": "Door of left-rear",
    "HouMen-Y": "Door of right-rear",
    "QianBaoXianGangPi": "Front bumper",
    "QianDaDeng-Z": "Headlamp of left",
    "QianDaDeng-Y": "Headlamp of right",
    "QianMen-Z": "Door of left-front",
    "QianMen-Y": "Door of right-front",
    "QianYiZiBan-Z": "Fender of left-front",
    "QianYiZiBan-Y": "Fender of right-front",
    "WaiWeiDeng-Z": "Outer Taillight of left",
    "WaiWeiDeng-Y": "Outer Taillight of right",
    "QianMenBoLiZuo": "Glass of the left-front door",
    "QianMenBoLiYou": "Glass of the right-front door",
    "QianFenDangBoLi": "Windshield of front",
    "HouFengDangBoLiJuShengMenBoLi": "Windshield of rear",
    "HouMenBoLiZuo": "Glass of the left-rear door",
    "HouMenBoLiYou": "Glass of the right-rear door",
    "DaoCheJingZongCheng-Z": "Rearview mirror of left",
    "DaoCheJingZongCheng-Y": "Rearview mirror of right",
    "GangQuan": "Steel rim",
    "DiDaBain-Z": "Bottom side of left",
    "DiDaBain-Y": "Bottom side of right",
    "QianWuDeng-Z": "Fog lamp of left-front",
    "QianWuDeng-Y": "Fog lamp of right-front",
    "QianWuDengHuZhao-Z": "Fog lamp shade of left-front",
    "QianWuDengHuZhao-Y": "Fog lamp shade of right-front",
}

part_chinese_name = {
    "boliposun": "玻璃破损",
    "boliliewen": "玻璃裂纹",
    "huahen": "划痕",
    "guaca": "刮擦",
    "aoxian": "凹陷",
    "zhezhou": "褶皱",
    "silie": "撕裂",
    "jichuan": "击穿",
    "queshi": "缺失",
    "Qian": "前",
    "Zuo": "左",
    "Hou": "后",
    "You": "右",
    "ZuoQian": "左前",
    "ZuoHou": "左后",
    "YouHou": "右后",
    "YouQian": "右前",
    "QianBaoXianGangPi": "前保险杠皮",
    "FaDongJiZhao": "发动机罩",
    "QianYiZiBan-Z": "前叶子板（左）",
    "A-Zhu-Z": "A柱（左）",
    "QianMen-Z": "前门壳（左）",
    "HouMen-Z": "后门壳（左）",
    "HouYeZiBan-Z": "后叶子板（左）",
    "DiDaBain-Z": "底大边（左）",
    "DiDaBain-Y": "底大边（右）",
    "HouBaoXianGangPi": "后保险杠皮",
    "XingLiXiangGai": "行李箱盖",
    "HouYeZiBan-Y": "后叶子板（右）",
    "HouMen-Y": "后门壳（右）",
    "QianMen-Y": "前门壳（右）",
    "QianYiZiBan-Y": "前叶子板（右）",
    "A-Zhu-Y": "A柱（右）",
    "CheDing": "车顶外板",
    "QianDaDeng-Z": "前大灯（左）",
    "QianWuDeng-Z": "前雾灯（左）",
    "QianDaDeng-Y": "前大灯（右）",
    "QianWuDeng-Y": "前雾灯（右）",
    "WaiWeiDeng-Z": "外尾灯（左）",
    "NeiWeiDeng-Z": "内尾灯（左）",
    "WaiWeiDeng-Y": "外尾灯（右）",
    "NeiWeiDeng-Y": "内尾灯（右）",
    "DaoCheJingZongCheng-Z": "倒车镜总成（左）",
    "DaoCheJingZongCheng-Y": "倒车镜总成（右）",
    "QianWuDengHuZhao-Z": "前雾灯护罩（左）",
    "QianWuDengHuZhao-Y": "前雾灯护罩（右）",
    "ZhongWang": "中网",
    "QianBaoXianGangXiaGeShan": "前保险杠下隔栅",
    "GangQuan": "钢圈",
    "HouFengDangBoLiJuShengMenBoLi": "举升门玻璃",
    "YouQianYeZiBanZhuanXiangDeng": "前叶子板灯（右）",
    "ZuoQianYeZiBanZhuanXiangDeng": "前叶子板灯（左）",
    "ZuoQianYeZiBanLunMei": "前叶子板轮眉（左）",
    "QianMenBoLiYou": "前门玻璃（右）",
    "HouMenBoLiYou": "后门玻璃（右）",
    "QianFenDangBoLi": "前风挡玻璃",
    "QianBaoXiaDuan": "前保险杠皮（下）",
    "ZuoQianMenShiTiao": "前门饰条（左）",
    "ZuoHouMenShiTiao": "后门饰条（左）",
    "ZuoQianMenShiBen": "前门饰板（左）",
    "HouMenSanJiaoBoLiYou": "后门三角玻璃（右）",
    "YouQianMenShiTiao": "前门饰条（右）",
    "YouHouMenShiTiao": "后门饰条（右）",
    "ZuoCeDiDaBianShiTiaoShiBen": "底大边饰条（左）",
    "HouCeWeiBoLiYou": "侧窗玻璃（右）",
    "HouCeWeiBoLiZuo": "侧窗玻璃（左）",
    "YouQianYeZiBanLunMei": "前叶子板轮眉（右）",
    "QianMenBoLiZuo": "前门玻璃（左）",
    "YouHouYeZiBanLunMei": "后轮眉（右）",
    "HouMenBoLiZuo": "后门玻璃（左）",
    "HouMenSanJiaoBoLiZuo": "后门三角玻璃（左）",
    "QianMenSanJiaoBoLiYou": "前门三角玻璃（右）",
    "YouQianMenShiBan": "前门饰板（右）",
    "ZuoHouMenShiBan": "后门饰板（左）",
    "YouHouMenShiBan": "后门饰板（右）",
    "ZuoHouYeZiBanLunMei": "后轮眉（左）",
    "YouCeDiDaBianShiTiaoShiBan": "底大边饰条（右）",
    "HouBaoXiaDuan": "后保险杠皮（下）",
    "QianMenSanJiaoBoLiZuo": "前门三角玻璃（左）",
    "BeiTaiZhao": "备胎罩",
    "YouQianYeZiBanShiBan": "前叶子板下饰板（右）",
    "ZuoQianYeZiBanShiBan": "前叶子板下饰板（左）",
}

part_index = {
    "boliposun": 0,
    "boliliewen": 1,
    "huahen": 2,
    "guaca": 3,
    "aoxian": 4,
    "zhezhou": 5,
    "silie": 6,
    "jichuan": 7,
    "queshi": 8,
    "Qian": 9,
    "Zuo": 10,
    "Hou": 11,
    "You": 12,
    "ZuoQian": 13,
    "ZuoHou": 14,
    "YouHou": 15,
    "YouQian": 16,
    "QianBaoXianGangPi": 17,
    "FaDongJiZhao": 18,
    "QianYiZiBan-Z": 19,
    "A-Zhu-Z": 20,
    "QianMen-Z": 21,
    "HouMen-Z": 22,
    "HouYeZiBan-Z": 23,
    "DiDaBian-Z": 24,
    "HouBaoXianGangPi": 25,
    "XingLiXiangGai": 26,
    "HouYeZiBan-Y": 27,
    "DiDaBain-Y": 28,
    "HouMen-Y": 29,
    "QianMen-Y": 30,
    "QianYiZiBan-Y": 31,
    "A-Zhu-Y": 32,
    "CheDing": 33,
    "QianDaDeng-Z": 34,
    "QianWuDeng-Z": 35,
    "QianDaDeng-Y": 36,
    "QianWuDeng-Y": 37,
    "WaiWeiDeng-Z": 38,
    "NeiWeiDeng-Z": 39,
    "WaiWeiDeng-Y": 40,
    "NeiWeiDeng-Y": 41,
    "DaoCheJingZongCheng-Z": 42,
    "DaoCheJingZongCheng-Y": 43,
    "QianWuDengHuZhao-Z": 44,
    "QianWuDengHuZhao-Y": 45,
    "ZhongWang": 46,
    "QianBaoXianGangXiaGeShan": 47,
    "GangQuan": 48,
    "HouFengDangBoLiJuShengMenBoLi": 49,
    "YouQianYeZiBanZhuanXiangDeng": 50,
    "ZuoQianYeZiBanZhuanXiangDeng": 51,
    "ZuoQianYeZiBanLunMei": 52,
    "QianMenBoLiYou": 53,
    "HouMenBoLiYou": 54,
    "QianFenDangBoLi": 55,
    "QianBaoXiaDuan": 56,
    "ZuoQianMenShiTiao": 57,
    "ZuoHouMenShiTiao": 58,
    "ZuoQianMenShiBen": 59,
    "HouMenSanJiaoBoLiYou": 60,
    "YouQianMenShiTiao": 61,
    "YouHouMenShiTiao": 62,
    "ZuoCeDiDaBianShiTiaoShiBen": 63,
    "HouCeWeiBoLiYou": 64,
    "HouCeWeiBoLiZuo": 65,
    "YouQianYeZiBanLunMei": 66,
    "QianMenBoLiZuo": 67,
    "YouHouYeZiBanLunMei": 68,
    "HouMenBoLiZuo": 69,
    "HouMenSanJiaoBoLiZuo": 70,
    "QianMenSanJiaoBoLiYou": 71,
    "YouQianMenShiBan": 72,
    "ZuoHouMenShiBan": 73,
    "YouHouMenShiBan": 74,
    "ZuoHouYeZiBanLunMei": 75,
    "YouCeDiDaBianShiTiaoShiBan": 76,
    "HouBaoXiaDuan": 77,
    "QianMenSanJiaoBoLiZuo": 78,
    "BeiTaiZhao": 79,
    "YouQianYeZiBanShiBan": 80,
    "ZuoQianYeZiBanShiBan": 81
}